platform :ios, '14.1'

source 'https://cdn.cocoapods.org/'

target 'KuiklyStockChat' do
  inhibit_all_warnings!

  # Kuikly iOS 渲染器（与 KUIKLY_VERSION 对齐：2.15.0-2.1.21）
  # 通过 maven 镜像查找 KuiklyIOSRender 的 CocoaPods 源
  pod 'OpenKuiklyIOSRender', '2.15.0'

  # 业务代码 Pod（由 ../shared/build.gradle.kts 的 cocoapods {} 自动生成）
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    end
  end
end
